In [1]:
# LSTM v1 - Simple Lstm experiments
from sequences.label_dictionary import LabelDictionary
dic = LabelDictionary([], start_index=1)

dic.add("a")
dic.add("b")
print dic

assert("a" == dic.get_label_name(dic["a"]))

{'a': 1, 'b': 2}


In [2]:
%load_ext autoreload
%autoreload 2

import readers.tac_prep_corpus as tc
from readers.tac_prep_corpus import *

print data_dir

readers/../data/


In [3]:
data_tac2014_train = data_dir+"/clear_data/data_tac2014_train.json"
data_tac2014_eval = data_dir+"/clear_data/data_tac2014_eval.json"
data_tac2015_train = data_dir+"/clear_data/data_tac2015_train.json"
data_tac2015_eval = data_dir+"/clear_data/data_tac2015_eval.json"

Vocab and statistics

In [4]:
# reload(readers.tac_prep_corpus)
word_counts = TacPrepJsonCorpus.word_counts_from_jsonfiles(json_files = [data_tac2014_train, data_tac2014_eval, data_tac2015_train])

# print "Top 10 tokens:"
# print word_counts[:10]

In [5]:
# word_counts.sort(key = lambda x:x[1], reverse=True)
print "Vocab size:%s" % len(word_counts)
print "Tokens with freq>=%s : %s" % (5, len( [xx for xx in word_counts if xx[1]>=5]))

Vocab size:20459
Tokens with freq>=5 : 6813


In [6]:
# clear the vocab
vocab = [xx[0] for xx in word_counts]
print vocab[-10:]

[u'toured', u'Merion', u'dependence', u'Advocacy', u'BEFORE', u'Musical', u'Fastow', u'Coach', u'six-party', u'volumes']


In [7]:
print len([xx for xx in vocab if ("/" in xx)or("\\" in xx)])


400


# Load the corpus

In [8]:
max_sent_len = 1000 
max_nr_sent = 100000
max_sent_len=max_sent_len
max_nr_sent=max_nr_sent
update_vocab=True
update_tags=True
unknown_word = "UNKNWN"
unknown_tag = "O"
mapping_file = None
data_x_fieldname = "tokens"
data_y_fieldname = "labels_event"



In [9]:
def count_non_zero_label(test_seq, zero_label=0):
    cnt = 0
    for item in test_seq:
        for lbl in item.y:
            if lbl != zero_label:
                cnt += 1
                # print item.y
                break

    return cnt

In [32]:
# Use indexes that start from 1 if you use TF dynamic sequences!
tag_start_index = 1
vocab_start_index = 1

In [33]:
tac_corpus = TacPrepJsonCorpus([unknown_word], [unknown_tag], 
                               tag_start_index=tag_start_index, 
                               vocab_start_index=vocab_start_index)

In [34]:
test_seq, test_seq_meta = tac_corpus.read_sequence_list_tac_json([data_tac2015_eval], max_sent_len=max_sent_len, max_nr_sent=max_nr_sent, 
                         update_vocab=update_vocab, update_tags=update_tags, unknown_word=unknown_word, 
                         unknown_tag=unknown_tag, mapping_file=mapping_file, 
                         data_x_fieldname=data_x_fieldname,
                         data_y_fieldname=data_y_fieldname)

readers/../data//clear_data/data_tac2015_eval.json


In [35]:
# print tac_corpus.word_dict

    

In [36]:

print "All sents:%s" % len(test_seq)
print "Non zero labels:%s" % count_non_zero_label(test_seq, zero_label = tag_start_index)
print test_seq_meta[0]["tokens"]
print test_seq[0].x
print test_seq[0].y
# print [tac_corpus.word_dict[a] for a in test_seq[0].x]


All sents:4164
Non zero labels:2646
[u'regime', u'<img\xa0src="http://www.amnesty.org/sites/impact.amnesty.org/files/imagecache/news-highlight/brazil-amnesty-law%2025.04.12.JPG"/>', u'The', u'efforts', u'of', u'federal', u'prosecutors', u'to', u'initiate', u'criminal', u'investigations', u'into', u'past', u'human', u'rights', u'violations', u'marks', u'a', u'crucial', u'moment', u'in', u'Brazil', u"'s", u'history', u',', u'said', u'Amnesty', u'International', u'after', u'federal', u'prosecutors', u'in', u'S\xe3o', u'Paulo', u'charged', u',', u'on', u'24', u'March', u'2012', u',', u'retired', u'Colonel', u'Carlos', u'Alberto', u'Brilhante', u'Ustra', u'and', u'police', u'chief', u'-LRB-', u'delegado', u'-RRB-', u'Dirceu', u'Garvina', u',', u'with', u'the', u'kidnapping', u'of', u'union', u'leader', u'Alu\xedzio', u'Palhano', u'Pedreira', u'Ferreira', u'in', u'1971', u'.']
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 7, 8, 2

In [37]:
train_seq, train_seq_meta = tac_corpus.read_sequence_list_tac_json([data_tac2014_train, data_tac2015_train], max_sent_len=max_sent_len, max_nr_sent=max_nr_sent, 
                         update_vocab=update_vocab, update_tags=update_tags, unknown_word=unknown_word, 
                         unknown_tag=unknown_tag, mapping_file=mapping_file, 
                         data_x_fieldname=data_x_fieldname,
                         data_y_fieldname=data_y_fieldname)

readers/../data//clear_data/data_tac2014_train.json
readers/../data//clear_data/data_tac2015_train.json


In [38]:
print "All sents:%s" % len(train_seq)
print "Non zero labels:%s" % count_non_zero_label(train_seq, zero_label = tag_start_index)


All sents:12573
Non zero labels:5367


In [39]:
dev_seq, dev_seq_meta = tac_corpus.read_sequence_list_tac_json([data_tac2014_eval], max_sent_len=max_sent_len, max_nr_sent=max_nr_sent, 
                         update_vocab=update_vocab, update_tags=update_tags, unknown_word=unknown_word, 
                         unknown_tag=unknown_tag, mapping_file=mapping_file, 
                         data_x_fieldname=data_x_fieldname,
                         data_y_fieldname=data_y_fieldname)

readers/../data//clear_data/data_tac2014_eval.json


In [18]:
print "All sents:%s" % len(dev_seq)
print "Non zero labels:%s" % count_non_zero_label(dev_seq, zero_label = tag_start_index)

All sents:9041
Non zero labels:3749


In [19]:
print train_seq.y_dict

# Redo indices
train_seq, test_seq, dev_seq = tc.compacify(train_seq, test_seq, dev_seq,
                                            default_vocab_dict=[unknown_word], 
                                            vocab_start_index=vocab_start_index, 
                                            default_tag_dict=[unknown_tag], 
                                            tag_start_index=tag_start_index,
                                            theano=True)



# Get number of words and tags in the corpus
nr_words = len(train_seq.x_dict)
nr_tags = len(train_seq.y_dict)



{u'B-EVENT': 2, 'O': 1, u'I-EVENT': 3}


In [20]:
for k,v in train_seq.x_dict.iteritems():
    #print k,v
    if v>nr_words:
        print (k,v)
        
print nr_words
print nr_tags

25584
3


# Run the lstm

In [21]:
# import lstm_v1 as lstm_v1
# import theano
# import theano.tensor as T

In [22]:
emb_size=50
hidden_size=50
SEED = 42

lrate = 0.0001

nr_iterations = 5
batch_size = 50
print "nr_words:%s" % nr_words
print "emb_size:%s" % emb_size
print "hidden_size:%s" % hidden_size
print "nr_tags:%s" % nr_tags
print "lrate:%s" % lrate



nr_words:25584
emb_size:50
hidden_size:50
nr_tags:3
lrate:0.0001


# Tensorflow 

In [23]:
import numpy as np
import tensorflow as tf



## Tensorflow padding and batching

In [24]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

# x = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "x")
# y = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "y")
# seq_len = tf.placeholder(dtype=tf.int64, shape=[None], name = "seq_len")

# batched_data = tf.train.batch(
#     tensors=[x, y, seq_len],
#     batch_size = batch_size,
#     dynamic_pad = True,
#     name="batch_data"
# )

In [25]:
# # data_x = np.array([np.array(a.x) for a in train_seq])
# # data_seq_len = np.array([len(a.x) for a in train_seq])
# # data_y = np.array([np.array(a.y) for a in train_seq])

# data_x = tf.convert_to_tensor([a.x.tolist() for a in train_seq], dtype=tf.int64)
# data_seq_len = tf.convert_to_tensor([len(a.x) for a in train_seq], dtype=tf.int64)
# data_y = tf.convert_to_tensor([a.y.tolist() for a in train_seq], dtype=tf.int64)

# print data_x[:5]
# print data_seq_len[:5]
# print data_y[:5]

In [26]:
# print(batched_data)
# print type(data_x)
# print type(data_y)
# print type(data_seq_len)

# #tf.reset_default_graph()

# # Run the graph
# # tf.contrib.learn takes care of starting the queues for us
# # res = sess.run(batched_data[0], batched_data[1], batched_data[2] , feed_dict={x:data_x, y:data_y, seq_len:data_seq_len})
# result = tf.contrib.learn.run_n(
#     {
#         "batched_data_x": batched_data[0],
#         "batched_data_y": batched_data[1],
#         "batched_data_seq_len": batched_data[2]
#     },
#     n=1,
#     feed_dict={x:data_x, 
#                seq_len:data_seq_len,
#                y:data_y})


# Print the result
# print("Batch shape: {}".format(res[0]["y"].shape))
# print(res[0]["y"])

## Bi LSTM
    

In [27]:
embeddings_number = nr_words
embedding_size = emb_size
n_classes = nr_tags
learning_rate=0.000001

print "embeddings_number:%s" % embeddings_number
print "embedding_size:%s" % embedding_size
print "n_classes:%s" % n_classes
print "learning_rate:%s" % learning_rate



tf.reset_default_graph()

# Define weights
weights = {
    # Hidden layer weights => 2*n_hidden because of forward + backward cells
    #'out': tf.Variable(tf.random_uniform([2*hidden_size, n_classes], minval=-1, maxval=1, dtype=tf.float64), name="out_w", dtype=tf.float64)
    'out': tf.Variable(tf.truncated_normal([2*hidden_size, n_classes], stddev=0.1, dtype=tf.float64), name="out_w", dtype=tf.float64)
}
biases = {
    # 'out': tf.Variable(tf.random_uniform([n_classes], minval=-1, maxval=1, dtype=tf.float64), name="out_b", dtype=tf.float64)
    'out': tf.Variable(tf.truncated_normal([n_classes], stddev=0.1, dtype=tf.float64), trainable=True, name="out_b", dtype=tf.float64)
}

input_x = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "input_x")
input_y = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "input_y") # this is not onehot!
input_y_mask = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "input_y_mask") # this is not onehot!
input_seq_len = tf.placeholder(dtype=tf.int64, shape=[None], name = "input_seq_len")

with tf.device('/cpu:0'), tf.name_scope("embeddings"):
    embeddings_placeholder = tf.placeholder(tf.float64, shape=[embeddings_number, embedding_size])
    # embeddings_tuned = tf.Variable(embeddings_placeholder)

    embedded_chars = tf.nn.embedding_lookup(embeddings_placeholder, input_x)
    # embedded_chars_expanded = tf.expand_dims(embedded_chars, -1)


def BiLSTM_dynamic(x_embedd, input_seq_len, 
                   use_peepholes=False, cell_clip=None,
                   # initializer=None, 
                   num_proj=None, proj_clip=None,
                   num_unit_shards=1, num_proj_shards=1,
                   forget_bias=1.0, state_is_tuple=True,
                   activation=tf.tanh):
    with tf.name_scope("BiLSTM"):
        with tf.variable_scope('forward'):
            cell_fw = tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, state_is_tuple=True,
                                               use_peepholes=use_peepholes, cell_clip=cell_clip,
                                               initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=42),
                                               num_proj=num_proj, proj_clip=proj_clip,
                                               num_unit_shards=num_unit_shards, num_proj_shards=num_proj_shards,
                                               forget_bias=forget_bias,
                                               activation=activation)

        with tf.variable_scope('backward'):    
            cell_bw = tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, state_is_tuple=True,
                                               use_peepholes=use_peepholes, cell_clip=cell_clip,
                                               initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=24), 
                                               num_proj=num_proj, proj_clip=proj_clip,
                                               num_unit_shards=num_unit_shards, num_proj_shards=num_proj_shards,
                                               forget_bias=forget_bias,
                                               activation=activation)

        outputs, states  = tf.nn.bidirectional_dynamic_rnn(
            cell_fw=cell_fw,
            cell_bw=cell_bw,
            dtype=tf.float64,
            sequence_length=input_seq_len,
            inputs=x_embedd)

    return outputs, states


outputs, states = BiLSTM_dynamic(x_embedd=embedded_chars, input_seq_len=input_seq_len, cell_clip=1)
output_fw, output_bw = outputs
states_fw, states_bw = states

# we use concatenation over the fw and bw outputs - some approaches use sum?
# output_concat = tf.concat(2, outputs) - we have to reverse and concat

output_bw_reversed = tf.reverse(output_bw,dims=(False, False, True))
outputs_rev = [output_fw, output_bw_reversed]

output_concat = tf.concat(2, outputs_rev)

# Calculate logits and probs
# Reshape so we can calculate them all at once
bi_output_concat_flat = tf.reshape(output_concat, [-1, 2*hidden_size])

bi_output_concat_flat_clipped = tf.clip_by_value(bi_output_concat_flat, -1., 1.)

logits_flat = tf.batch_matmul(bi_output_concat_flat_clipped, weights["out"]) + biases["out"]
logits_flat = tf.clip_by_value(logits_flat, -1., 1.)
probs_flat = tf.nn.softmax(logits_flat)

print "outputs[-1].shape:%s" % outputs[-1]#
print "weights[\"out\"]].shape:%s" % weights["out"]#.shape
print "biases[\"out\"].shape:%s" % biases["out"]#.shape

# print pred

#make y flat so it match pred shape
input_y_flat =  tf.reshape(input_y, [-1])
input_y_mask_flat = tf.reshape(input_y_mask, [-1]) 
print "input_y_flat:%s" % input_y_flat
# # Define loss and optimizer

# sparse softmax cros entropy - aka - calculates on non-onehot y!

losses = tf.nn.sparse_softmax_cross_entropy_with_logits(logits_flat, input_y_flat) 

def tf_nan_to_zeros_float64(tensor):
    return tf.select(tf.is_nan(tensor), tf.zeros(tf.shape(tensor), dtype=tf.float64),tensor)

losses = tf_nan_to_zeros_float64(losses)

# losses = tf.select()

# optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(losses)
# optimizer = tf.train.AdamOptimizer(learning_rate=0.001).minimize(losses)
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00).minimize(losses)
learn_rate = tf.Variable(0.01, trainable=False)
# optimizer = tf.train.GradientDescentOptimizer(learn_rate).minimize(losses)
#optimizer = tf.train.GradientDescentOptimizer(learn_rate)
optimizer = tf.train.AdamOptimizer(learning_rate=learn_rate)

gvs = optimizer.compute_gradients(losses)
capped_gvs = [(tf.clip_by_value(tf_nan_to_zeros_float64(grad), -1., 1.), var) for grad, var in gvs]
apply_grads_op=optimizer.apply_gradients(capped_gvs)


# Mask the losses - padded values are zeros
#mask = tf.sign(tf.cast(input_y_mask_flat, dtype=tf.float64))
mask = tf.sign(tf.cast(input_y_flat, dtype=tf.float64))
print "mask:%s" % mask
masked_losses = mask * losses

# Bring back to [batch, class_num] shape
masked_losses = tf.reshape(masked_losses,  tf.shape(input_y))

input_seq_len_float = tf.cast(input_seq_len, dtype=tf.float64)

# Calculate mean loss - depending on the dynamic number of elements
mean_loss_by_example = tf.reduce_sum(masked_losses, reduction_indices=1) / input_seq_len_float
mean_loss = tf.reduce_mean(mean_loss_by_example)

# # Evaluate model
print "probs_flat:%s" % probs_flat
print "input_y:%s" % input_y

preds = tf.argmax(probs_flat,1)

preds_non_paddings = tf.gather(preds, tf.where(tf.greater(input_y_flat, [0])))
input_y_non_paddings = tf.gather(input_y_flat, tf.where(tf.greater(input_y_flat, [0])))

correct_pred = tf.equal(preds_non_paddings, input_y_non_paddings)

accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float64))

print "The model might be okay :D"



embeddings_number:25584
embedding_size:50
n_classes:3
learning_rate:1e-06
outputs[-1].shape:Tensor("BiLSTM/ReverseSequence:0", shape=(?, ?, 50), dtype=float64)
weights["out"]].shape:<tensorflow.python.ops.variables.Variable object at 0x7fc378d3a5d0>
biases["out"].shape:<tensorflow.python.ops.variables.Variable object at 0x7fc37c5b9d10>
input_y_flat:Tensor("Reshape_1:0", shape=(?,), dtype=int64)
mask:Tensor("Sign:0", shape=(?,), dtype=float64)
probs_flat:Tensor("Softmax:0", shape=(?, 3), dtype=float64)
input_y:Tensor("input_y:0", shape=(?, ?), dtype=int64)
The model might be okay :D


In [28]:
# embeddings
embeddings_random = 0.01*np.random.uniform(size=(embeddings_number, embedding_size))
# embeddings_random[0][0] = float('nan')

nan_vals = 0

print np.isnan(np.sum(embeddings_random))
# for i in range(len(embeddings_random)):
#     for j in range(embeddings_random.shape[1]):
#         if np.isNan(embeddings_random[i][j]):
#             nan_vals +=1
# print nan_vals

False


In [29]:
#Padding
def pad(seq, pad_value, to_size):
    pad_seq = []
    if len(seq) > to_size:
        pad_seq = seq[:to_size]
    else:
        pad_seq = seq[:] + [pad_value]*(to_size - len(seq))
        
    return pad_seq

print pad([1,2,3], 0, 8)
print pad([1,2,3,4,5,6,7,8], 0, 8)
print pad([1,2,3,4,5,6,7,8,9,10], 0, 8)
        


[1, 2, 3, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [30]:
import time as ti
pad_value = 0
batches_cnt = len(train_seq)/batch_size
print "Batches:%s" % batches_cnt
#batches_cnt = min(batches_cnt, 1)

# Initializing the variables
init = tf.initialize_all_variables()
sess = tf.InteractiveSession()
sess.run(init, feed_dict = {embeddings_placeholder : embeddings_random})


epochs_cnt = 10
#train with batches
max_len = 0
print "Start training in %s epochs" % epochs_cnt
for epoch in range(0, epochs_cnt):
    print "Epoch %d:" % (epoch+1),
    start = ti.time()
    for i in range(0, batches_cnt):
        print"batch %s =================" %(i+1)
        #print i
        batch_data = train_seq[i*batch_size:i*batch_size+batch_size]

        batch_data_seqlens = [len(a.x) for a in batch_data]
        #print data_lens
        prev_max_len= max_len
        max_len = max(batch_data_seqlens)
        print "max_len:%s" % max_len
        print "prev_max_len:%s" % prev_max_len
        batch_data_padded_x = [pad(a.x.tolist(), pad_value, max_len) for a in batch_data]
        batch_data_padded_x_embedd = [[pad(a.x.tolist(), pad_value, max_len)] for a in batch_data]
        batch_data_padded_y = [pad(a.y.tolist(), pad_value, max_len) for a in batch_data]
        batch_data_padded_y_mask = [[1 if item>0 else 0 for item in pad(a.y.tolist(), pad_value, max_len)] for a in batch_data]

        feed_dict = {
            embeddings_placeholder : embeddings_random,
            input_x : batch_data_padded_x,
            input_y : batch_data_padded_y,
            input_y_mask : batch_data_padded_y_mask,
            input_seq_len: batch_data_seqlens
        }

        #_, \
        _,\
        res_cost, res_acc, res_mean_loss_by_example, \
        res_logits_flat,\
        res_losses, \
        res_probs_flat,\
        res_input_seq_len_float, \
        res_input_y_flat, res_bi_output_concat_flat,\
        res_output_fw, res_output_bw_reversed, res_embedded_chars,\
        res_weights_out, res_biases_out,\
        res_capped_gvs,\
        res_gvs \
        = sess.run([
         #               optimizer, 
                        apply_grads_op,
                        mean_loss, 
                        accuracy, 
                        mean_loss_by_example, 
                        logits_flat,
                        losses, 
                        probs_flat,
                        input_seq_len_float,
                        input_y_flat, bi_output_concat_flat,
                          output_fw, output_bw_reversed, embedded_chars,
                        weights["out"], biases["out"],
                        capped_gvs,
                        gvs], 
                 feed_dict=feed_dict)
        print "batch %s cost=%s, acc=%s:" %(i+1, res_cost, res_acc)
        
        # print "res_input_seq_len_float:%s" % res_input_seq_len_float
        has_nans = False
        # res_output_concat =  sess.run(output_concat, feed_dict=feed_dict)
        # print res_output_concat.shape
        if np.isnan(np.sum(res_embedded_chars)):
            has_nans = True
            print "[res_embedded_chars] has nans!"
        
        if np.isnan(np.sum(res_output_fw)):
            has_nans = True
            print "[res_output_fw] has nans!"
            
        if np.isnan(np.sum(res_output_bw_reversed)):
            has_nans = True
            print "[res_output_bw_reversed] has nans!"
            
        if np.isnan(np.sum(res_bi_output_concat_flat)):
            has_nans = True
            print "[res_bi_output_concat_flat] has nans!"
        
        if np.isnan(np.sum(res_weights_out)):
            has_nans = True
            print "[res_weights_out] has nans!"
            
        if np.isnan(np.sum(res_biases_out)):
            has_nans = True
            print "[res_biases_out] has nans!"            
            
        if np.isnan(np.sum(res_logits_flat)):
            has_nans = True
            print "[res_logits_flat] has nans!"
        
        if np.isnan(np.sum(res_probs_flat)):
            has_nans = True
            print "[res_probs_flat] has nans!"
        
        if np.isnan(np.sum(res_losses)):
            has_nans = True
            print "[res_losses] has nans!"
            
        if np.isnan(np.sum(res_mean_loss_by_example)):
            has_nans = True
            print "[res_mean_loss_by_example] has nans!"
            
        if np.isnan(res_cost):
            has_nans = True
            print "[res_cost] has nans!"
            
#         if np.isnan(res_gvs):
#             has_nans = True
#             print "[res_gvs] has nans!"
        
#         if np.isnan(res_capped_gvs):
#             has_nans = True
#             print "[res_capped_gvs] has nans!"
    
        print "res_weights_out:%s" % res_weights_out[:5]
        
        if has_nans:
            print "res_weights_out:%s" % res_weights_out[:5]
            print "res_biases_out:%s" % res_biases_out
            print "batch_data_padded_x:%s" % batch_data_padded_x[0]
            print "res_embedded_chars:%s" % len(res_embedded_chars), len(res_embedded_chars[0])
            print "res_output_fw:%s" % res_output_fw[0]
            print "res_output_bw_reversed:%s" % res_output_bw_reversed[0]
            # print "res_bi_output_concat_flat:%s" % res_bi_output_concat_flat
            print "res_input_y_flat:%s" % res_input_y_flat
            print "res_logits_flat:%s" % res_logits_flat
            print "res_res_probs_flat:%s" % res_probs_flat
            print "res_mean_loss_by_example:%s" % res_mean_loss_by_example
            print "res_losses:%s" % res_losses
            print "res_capped_gvs:%s" % res_capped_gvs
            print "res_gvs:%s" % res_gvs
            
            res_losses_reshaped = res_losses.reshape([50, res_losses.shape[0]/50])
            for i in range(len(res_losses_reshaped)):
                if np.isnan(np.sum(res_losses_reshaped[i])):
                    print res_losses_reshaped[i]
            raise Exception("Fucking NANS!")
#             has_nans =  np.isnan(np.sum(res_bi_output_concat_flat))
#             if has_nans:
#                 raise Exception("Fucking NANS - res_bi_output_concat_flat!")

    print " Train cost %2.2f Train Acc %2.2f %% in %s\n" % (res_cost, res_acc, ti.time()-start),
    #print batch_data_padded_x
    #print batch_data_padded_y
    

Batches:251


Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7fc392d28310>> ignored


Start training in 10 epochs
Epoch 1: batch 1 =================
max_len:38
prev_max_len:0
batch 1 cost=1.21936648096, acc=0.0:
res_weights_out:[[-0.18737399  0.08245063 -0.02139274]
 [ 0.14476126 -0.03200227 -0.08631308]
 [-0.02467666 -0.00528742 -0.09195036]
 [-0.15897545  0.14415284  0.08556138]
 [-0.12183505 -0.04553379  0.03496532]]
batch 2 =================
max_len:45
prev_max_len:38
batch 2 cost=1.17101906805, acc=0.0:
res_weights_out:[[-0.19600126  0.0918468  -0.02998477]
 [ 0.15093756 -0.03688161 -0.08007199]
 [-0.03016175 -0.00175664 -0.09751806]
 [-0.16716409  0.15293986  0.07739249]
 [-0.12913721 -0.03836604  0.02765558]]
batch 3 =================
max_len:59
prev_max_len:45
batch 3 cost=1.05860053518, acc=0.83356258597:
res_weights_out:[[-0.20267014  0.09911004 -0.03662641]
 [ 0.15571185 -0.04065335 -0.07524762]
 [-0.03440174  0.00097265 -0.1018219 ]
 [-0.1734939   0.15973222  0.07107793]
 [-0.13478178 -0.03282537  0.02200515]]
batch 4 =================
max_len:64
prev_max_le

In [31]:
# import time as ti
# pad_value = 0
# batches_cnt = len(train_seq)/batch_size
# print "Batches:%s" % batches_cnt
# #batches_cnt = min(batches_cnt, 1)

# # Initializing the variables
# init = tf.initialize_all_variables()
# sess = tf.InteractiveSession()
# sess.run(init, feed_dict = {embeddings_placeholder : embeddings_random})


# epochs_cnt = 10
# #train with batches
# print "Start training in %s epochs" % epochs_cnt
# for epoch in range(0, epochs_cnt):
#     print "Epoch %d:" % (epoch+1),
#     start = ti.time()
#     for i in range(0, batches_cnt):
#         print"batch %s =================" %(i+1)
#         #print i
#         batch_data = train_seq[i*batch_size:i*batch_size+batch_size]

#         batch_data_seqlens = [len(a.x) for a in batch_data]
#         #print data_lens
#         max_len = max(batch_data_seqlens)
#         #print max_len
#         batch_data_padded_x = [pad(a.x.tolist(), pad_value, max_len) for a in batch_data]
#         batch_data_padded_x_embedd = [[pad(a.x.tolist(), pad_value, max_len)] for a in batch_data]
#         batch_data_padded_y = [pad(a.y.tolist(), pad_value, max_len) for a in batch_data]
#         batch_data_padded_y_mask = [[1 if item>0 else 0 for item in pad(a.y.tolist(), pad_value, max_len)] for a in batch_data]

#         feed_dict = {
#             embeddings_placeholder : embeddings_random,
#             input_x : batch_data_padded_x,
#             input_y : batch_data_padded_y,
#             input_y_mask : batch_data_padded_y_mask,
#             input_seq_len: batch_data_seqlens
#         }

#         _, res_cost, res_acc, res_mean_loss_by_example, \
#                 res_losses, res_input_y_flat, res_bi_output_concat_flat,\
#             res_output_fw, res_output_bw_reversed, res_embedded_chars = \
#                  sess.run([optimizer, mean_loss, accuracy, mean_loss_by_example, 
#                            losses, input_y_flat, bi_output_concat_flat,
#                           output_fw, output_bw_reversed, embedded_chars], 
#                  feed_dict=feed_dict)
#         print "batch %s cost=%s, acc=%s:" %(i+1, res_cost, res_acc)
#         # res_output_concat =  sess.run(output_concat, feed_dict=feed_dict)
#         # print res_output_concat.shape
#         print "batch_data_padded_x:%s" % batch_data_padded_x[0]
#         has_nans =  np.isnan(np.sum(res_embedded_chars))
#         print "res_embedded_chars:%s" % len(res_embedded_chars), len(res_embedded_chars[0])
#         print "res_output_fw:%s" % res_output_fw[0]
#         print "res_output_bw_reversed:%s" % res_output_bw_reversed[0]
#         print "res_bi_output_concat_flat:%s" % res_bi_output_concat_flat
#         print "res_input_y_flat:%s" % res_input_y_flat
#         print "res_mean_loss_by_example:%s" % res_mean_loss_by_example
#         print "res_losses:%s" % res_losses
#         if has_nans:
#             raise Exception("Fucking NANS!")
    
#     print " Train cost %2.2f Train Acc %2.2f %% in %s\n" % (res_cost, res_acc, ti.time()-start),
#     #print batch_data_padded_x
#     #print batch_data_padded_y
    