In [1]:
# LSTM v1 - Simple Lstm experiments
from sequences.label_dictionary import LabelDictionary
dic = LabelDictionary([], start_index=1)

dic.add("a")
dic.add("b")
print dic

assert("a" == dic.get_label_name(dic["a"]))

{'a': 1, 'b': 2}


In [2]:
%load_ext autoreload
%autoreload 2

import readers.tac_prep_corpus as tc
from readers.tac_prep_corpus import *

print data_dir

readers/../data/


In [3]:
data_tac2014_train = data_dir+"/clear_data/data_tac2014_train.json"
data_tac2014_eval = data_dir+"/clear_data/data_tac2014_eval.json"
data_tac2015_train = data_dir+"/clear_data/data_tac2015_train.json"
data_tac2015_eval = data_dir+"/clear_data/data_tac2015_eval.json"

Vocab and statistics

In [4]:
# reload(readers.tac_prep_corpus)
word_counts = TacPrepJsonCorpus.word_counts_from_jsonfiles(json_files = [data_tac2014_train, data_tac2014_eval, data_tac2015_train])

# print "Top 10 tokens:"
# print word_counts[:10]

In [5]:
# word_counts.sort(key = lambda x:x[1], reverse=True)
print "Vocab size:%s" % len(word_counts)
print "Tokens with freq>=%s : %s" % (5, len( [xx for xx in word_counts if xx[1]>=5]))

Vocab size:20459
Tokens with freq>=5 : 6813


In [6]:
# clear the vocab
vocab = [xx[0] for xx in word_counts]
print vocab[-10:]

[u'toured', u'Merion', u'dependence', u'Advocacy', u'BEFORE', u'Musical', u'Fastow', u'Coach', u'six-party', u'volumes']


In [7]:
print len([xx for xx in vocab if ("/" in xx)or("\\" in xx)])


400


# Load the corpus

In [8]:
max_sent_len = 1000 
max_nr_sent = 100000
max_sent_len=max_sent_len
max_nr_sent=max_nr_sent
update_vocab=True
update_tags=True
unknown_word = "UNKNWN"
unknown_tag = "O"
mapping_file = None
data_x_fieldname = "tokens"
data_y_fieldname = "labels_event"



In [9]:
def count_non_zero_label(test_seq, zero_label=0):
    cnt = 0
    for item in test_seq:
        for lbl in item.y:
            if lbl != zero_label:
                cnt += 1
                # print item.y
                break

    return cnt

In [10]:
# Use indexes that start from 1 if you use TF dynamic sequences!
tag_start_index = 1
vocab_start_index = 1

In [11]:
tac_corpus = TacPrepJsonCorpus([unknown_word], [unknown_tag], 
                               tag_start_index=tag_start_index, 
                               vocab_start_index=vocab_start_index)

In [12]:
test_seq, test_seq_meta = tac_corpus.read_sequence_list_tac_json([data_tac2015_eval], max_sent_len=max_sent_len, max_nr_sent=max_nr_sent, 
                         update_vocab=update_vocab, update_tags=update_tags, unknown_word=unknown_word, 
                         unknown_tag=unknown_tag, mapping_file=mapping_file, 
                         data_x_fieldname=data_x_fieldname,
                         data_y_fieldname=data_y_fieldname)

readers/../data//clear_data/data_tac2015_eval.json


In [13]:
# print tac_corpus.word_dict

    

In [14]:

print "All sents:%s" % len(test_seq)
print "With non zero labels:%s" % count_non_zero_label(test_seq, zero_label = tag_start_index)
print test_seq_meta[0]["tokens"]
print test_seq[0].x
print test_seq[0].y
# print [tac_corpus.word_dict[a] for a in test_seq[0].x]


All sents:4164
With non zero labels:2646
[u'regime', u'<img\xa0src="http://www.amnesty.org/sites/impact.amnesty.org/files/imagecache/news-highlight/brazil-amnesty-law%2025.04.12.JPG"/>', u'The', u'efforts', u'of', u'federal', u'prosecutors', u'to', u'initiate', u'criminal', u'investigations', u'into', u'past', u'human', u'rights', u'violations', u'marks', u'a', u'crucial', u'moment', u'in', u'Brazil', u"'s", u'history', u',', u'said', u'Amnesty', u'International', u'after', u'federal', u'prosecutors', u'in', u'S\xe3o', u'Paulo', u'charged', u',', u'on', u'24', u'March', u'2012', u',', u'retired', u'Colonel', u'Carlos', u'Alberto', u'Brilhante', u'Ustra', u'and', u'police', u'chief', u'-LRB-', u'delegado', u'-RRB-', u'Dirceu', u'Garvina', u',', u'with', u'the', u'kidnapping', u'of', u'union', u'leader', u'Alu\xedzio', u'Palhano', u'Pedreira', u'Ferreira', u'in', u'1971', u'.']
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 7,

In [15]:
train_seq, train_seq_meta = tac_corpus.read_sequence_list_tac_json([data_tac2014_train, data_tac2015_train], max_sent_len=max_sent_len, max_nr_sent=max_nr_sent, 
                         update_vocab=update_vocab, update_tags=update_tags, unknown_word=unknown_word, 
                         unknown_tag=unknown_tag, mapping_file=mapping_file, 
                         data_x_fieldname=data_x_fieldname,
                         data_y_fieldname=data_y_fieldname)

readers/../data//clear_data/data_tac2014_train.json
readers/../data//clear_data/data_tac2015_train.json


In [16]:
print "All sents:%s" % len(train_seq)
print "With non zero labels:%s" % count_non_zero_label(train_seq, zero_label = tag_start_index)


All sents:12573
With non zero labels:5367


In [17]:
dev_seq, dev_seq_meta = tac_corpus.read_sequence_list_tac_json([data_tac2014_eval], max_sent_len=max_sent_len, max_nr_sent=max_nr_sent, 
                         update_vocab=update_vocab, update_tags=update_tags, unknown_word=unknown_word, 
                         unknown_tag=unknown_tag, mapping_file=mapping_file, 
                         data_x_fieldname=data_x_fieldname,
                         data_y_fieldname=data_y_fieldname)

readers/../data//clear_data/data_tac2014_eval.json


In [18]:
print "All sents:%s" % len(dev_seq)
print "With non zero labels:%s" % count_non_zero_label(dev_seq, zero_label = tag_start_index)

All sents:9041
With non zero labels:3749


In [19]:
print train_seq.y_dict

# Redo indices
train_seq, test_seq, dev_seq = tc.compacify(train_seq, test_seq, dev_seq,
                                            default_vocab_dict=[unknown_word], 
                                            vocab_start_index=vocab_start_index, 
                                            default_tag_dict=[unknown_tag], 
                                            tag_start_index=tag_start_index,
                                            theano=True)



# Get number of words and tags in the corpus
nr_words = len(train_seq.x_dict)
nr_tags = len(train_seq.y_dict)


{u'B-EVENT': 2, 'O': 1, u'I-EVENT': 3}


In [20]:
for k,v in train_seq.x_dict.iteritems():
    #print k,v
    if v>nr_words:
        print (k,v)
        
print nr_words
print nr_tags

25584
3


# Run the lstm

In [21]:
# import lstm_v1 as lstm_v1
# import theano
# import theano.tensor as T

In [22]:
emb_size=50
hidden_size=50
SEED = 42

lrate = 0.0001

nr_iterations = 5
batch_size = 50
print "nr_words:%s" % nr_words
print "emb_size:%s" % emb_size
print "hidden_size:%s" % hidden_size
print "nr_tags:%s" % nr_tags
print "lrate:%s" % lrate



nr_words:25584
emb_size:50
hidden_size:50
nr_tags:3
lrate:0.0001


# Tensorflow 

In [23]:
import numpy as np
import tensorflow as tf



## Tensorflow padding and batching

In [24]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

# x = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "x")
# y = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "y")
# seq_len = tf.placeholder(dtype=tf.int64, shape=[None], name = "seq_len")

# batched_data = tf.train.batch(
#     tensors=[x, y, seq_len],
#     batch_size = batch_size,
#     dynamic_pad = True,
#     name="batch_data"
# )

In [25]:
# # data_x = np.array([np.array(a.x) for a in train_seq])
# # data_seq_len = np.array([len(a.x) for a in train_seq])
# # data_y = np.array([np.array(a.y) for a in train_seq])

# data_x = tf.convert_to_tensor([a.x.tolist() for a in train_seq], dtype=tf.int64)
# data_seq_len = tf.convert_to_tensor([len(a.x) for a in train_seq], dtype=tf.int64)
# data_y = tf.convert_to_tensor([a.y.tolist() for a in train_seq], dtype=tf.int64)

# print data_x[:5]
# print data_seq_len[:5]
# print data_y[:5]

In [26]:
# print(batched_data)
# print type(data_x)
# print type(data_y)
# print type(data_seq_len)

# #tf.reset_default_graph()

# # Run the graph
# # tf.contrib.learn takes care of starting the queues for us
# # res = sess.run(batched_data[0], batched_data[1], batched_data[2] , feed_dict={x:data_x, y:data_y, seq_len:data_seq_len})
# result = tf.contrib.learn.run_n(
#     {
#         "batched_data_x": batched_data[0],
#         "batched_data_y": batched_data[1],
#         "batched_data_seq_len": batched_data[2]
#     },
#     n=1,
#     feed_dict={x:data_x, 
#                seq_len:data_seq_len,
#                y:data_y})


# Print the result
# print("Batch shape: {}".format(res[0]["y"].shape))
# print(res[0]["y"])

## Bi LSTM
    

In [27]:
embeddings_number = nr_words
embedding_size = emb_size
n_classes = nr_tags
learning_rate=0.1

print "embeddings_number:%s" % embeddings_number
print "embedding_size:%s" % embedding_size
print "n_classes:%s" % n_classes
print "learning_rate:%s" % learning_rate



tf.reset_default_graph()

# Define weights
weights = {
    # Hidden layer weights => 2*n_hidden because of forward + backward cells
    #'out': tf.Variable(tf.random_uniform([2*hidden_size, n_classes], minval=-1, maxval=1, dtype=tf.float64), name="out_w", dtype=tf.float64)
    'out': tf.Variable(tf.truncated_normal([2*hidden_size, n_classes], stddev=0.1, dtype=tf.float64), trainable=True, name="out_w", dtype=tf.float64)
}
biases = {
    # 'out': tf.Variable(tf.random_uniform([n_classes], minval=-1, maxval=1, dtype=tf.float64), name="out_b", dtype=tf.float64)
    'out': tf.Variable(tf.truncated_normal([n_classes], stddev=0.1, dtype=tf.float64), trainable=True, name="out_b", dtype=tf.float64)
}

input_x = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "input_x")
input_y = tf.placeholder(dtype=tf.int64, shape=[None, None], name = "input_y") # this is not onehot!
input_seq_len = tf.placeholder(dtype=tf.int64, shape=[None], name = "input_seq_len")

with tf.device('/cpu:0'), tf.name_scope("embeddings"):
    embeddings_placeholder = tf.placeholder(tf.float64, shape=[embeddings_number, embedding_size])
    # embeddings_tuned = tf.Variable(embeddings_placeholder)
    
    embeddings_tuned =tf.Variable(tf.truncated_normal([embeddings_number, embedding_size], stddev=0.1, dtype=tf.float64), trainable=True, name="out_w", dtype=tf.float64)
    embedded_chars = tf.nn.embedding_lookup(embeddings_tuned, input_x)
    # embedded_chars_expanded = tf.expand_dims(embedded_chars, -1)


def BiLSTM_dynamic(x_embedd, input_seq_len, shared_fw_bw=False,
                   use_peepholes=False, cell_clip=None,
                   # initializer=None, 
                   num_proj=None, proj_clip=None,
                   num_unit_shards=1, num_proj_shards=1,
                   forget_bias=1.0, state_is_tuple=True,
                   activation=tf.tanh):
    with tf.name_scope("BiLSTM"):
        with tf.variable_scope('forward'):
            cell_fw = tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, state_is_tuple=True,
                                               use_peepholes=use_peepholes, cell_clip=cell_clip,
                                               initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=42),
                                               num_proj=num_proj, proj_clip=proj_clip,
                                               num_unit_shards=num_unit_shards, num_proj_shards=num_proj_shards,
                                               forget_bias=forget_bias,
                                               activation=activation)

        with tf.variable_scope('backward'):    
            cell_bw = tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, state_is_tuple=True,
                                               use_peepholes=use_peepholes, cell_clip=cell_clip,
                                               initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=24), 
                                               num_proj=num_proj, proj_clip=proj_clip,
                                               num_unit_shards=num_unit_shards, num_proj_shards=num_proj_shards,
                                               forget_bias=forget_bias,
                                               activation=activation)

        outputs, states  = tf.nn.bidirectional_dynamic_rnn(
            cell_fw=cell_fw,
            cell_bw=cell_fw if shared_fw_bw else cell_bw,
            dtype=tf.float64,
            sequence_length=input_seq_len,
            inputs=x_embedd)

    return outputs, states


outputs, states = BiLSTM_dynamic(x_embedd=embedded_chars, input_seq_len=input_seq_len, cell_clip=None, shared_fw_bw=True)
output_fw, output_bw = outputs
states_fw, states_bw = states

# we use concatenation over the fw and bw outputs - some approaches use sum?
# output_concat = tf.concat(2, outputs) - we have to reverse and concat

output_bw_reversed = tf.reverse(output_bw,dims=(False, False, True))
outputs_rev = [output_fw, output_bw_reversed]

output_concat = tf.concat(2, outputs_rev)

# Calculate logits and probs
# Reshape so we can calculate them all at once
bi_output_concat_flat = tf.reshape(output_concat, [-1, 2*hidden_size])
# bi_output_concat_flat_clipped = tf.clip_by_value(bi_output_concat_flat, -1., 1.)

logits_flat = tf.batch_matmul(bi_output_concat_flat, weights["out"]) + biases["out"]
# logits_flat = tf.clip_by_value(logits_flat, -1., 1.)
probs_flat = tf.nn.softmax(logits_flat)

print "outputs[-1].shape:%s" % outputs[-1]#
print "weights[\"out\"]].shape:%s" % weights["out"]#.shape
print "biases[\"out\"].shape:%s" % biases["out"]#.shape

# print pred

#make y flat so it match pred shape
input_y_flat =  tf.reshape(input_y, [-1])
print "input_y_flat:%s" % input_y_flat
# # Define loss and optimizer

def tf_nan_to_zeros_float64(tensor):
    return tf.select(tf.is_nan(tensor), tf.zeros(tf.shape(tensor), dtype=tf.float64),tensor)
# sparse softmax cros entropy - aka - calculates on non-onehot y!
losses = tf.nn.sparse_softmax_cross_entropy_with_logits(logits_flat, input_y_flat) 
# replace nans with zeros
losses = tf_nan_to_zeros_float64(losses)

learn_rate = tf.Variable(learning_rate, trainable=False)

#Applying compute and apply gradients
optimizer = tf.train.AdamOptimizer(learning_rate=learn_rate)

gvs = optimizer.compute_gradients(losses)
capped_gvs = [(tf.clip_by_value(tf_nan_to_zeros_float64(grad), -1., 1.), var) for grad, var in gvs]

apply_grads_op=optimizer.apply_gradients(capped_gvs)


## Calculate the accuracy
# Mask the losses - padded values are zeros
mask = tf.sign(tf.cast(input_y_flat, dtype=tf.float64))
print "mask:%s" % mask
masked_losses = mask * losses

# Bring back to [batch, class_num] shape
masked_losses = tf.reshape(masked_losses,  tf.shape(input_y))

input_seq_len_float = tf.cast(input_seq_len, dtype=tf.float64)

# Calculate mean loss - depending on the dynamic number of elements
mean_loss_by_example = tf.reduce_sum(masked_losses, reduction_indices=1) / input_seq_len_float
mean_loss = tf.reduce_mean(mean_loss_by_example)

# # Evaluate model
print "probs_flat:%s" % probs_flat
print "input_y:%s" % input_y

preds_flat = tf.argmax(probs_flat,1)

preds_non_paddings = tf.gather(preds_flat, tf.where(tf.greater(input_y_flat, [0])))
input_y_non_paddings = tf.gather(input_y_flat, tf.where(tf.greater(input_y_flat, [0])))

preds_y = tf.reshape(preds_flat, tf.shape(input_y))

correct_pred = tf.equal(preds_non_paddings, input_y_non_paddings)

accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float64))

print "The model might be okay :D"



embeddings_number:25584
embedding_size:50
n_classes:3
learning_rate:0.1
outputs[-1].shape:Tensor("BiLSTM/ReverseSequence:0", shape=(?, ?, 50), dtype=float64)
weights["out"]].shape:<tensorflow.python.ops.variables.Variable object at 0x7fd139b81690>
biases["out"].shape:<tensorflow.python.ops.variables.Variable object at 0x7fd13569ae10>
input_y_flat:Tensor("Reshape_1:0", shape=(?,), dtype=int64)
mask:Tensor("Sign:0", shape=(?,), dtype=float64)
probs_flat:Tensor("Softmax:0", shape=(?, 3), dtype=float64)
input_y:Tensor("input_y:0", shape=(?, ?), dtype=int64)
The model might be okay :D


In [28]:
# embeddings
embeddings_random = 0.01*np.random.uniform(size=(embeddings_number, embedding_size))
# embeddings_random[0][0] = float('nan')

nan_vals = 0

print np.isnan(np.sum(embeddings_random))
# for i in range(len(embeddings_random)):
#     for j in range(embeddings_random.shape[1]):
#         if np.isNan(embeddings_random[i][j]):
#             nan_vals +=1
# print nan_vals

False


In [29]:
#Padding
def pad(seq, pad_value, to_size):
    pad_seq = []
    if len(seq) > to_size:
        pad_seq = seq[:to_size]
    else:
        pad_seq = seq[:] + [pad_value]*(to_size - len(seq))
        
    return pad_seq

print pad([1,2,3], 0, 8)
print pad([1,2,3,4,5,6,7,8], 0, 8)
print pad([1,2,3,4,5,6,7,8,9,10], 0, 8)
        


[1, 2, 3, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [30]:
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix([0, 0, 1, 1], [0,0,1,0])
classes_dict = dict([(v,k) for (k,v) in train_seq.y_dict.items()])
print classes_dict

def print_acc_from_conf_matrix(conf_matrix, classes_dict):
    for lblid in range(conf_matrix.shape[0]):
        overl_cnt = np.sum(conf_matrix[lblid])
        true_cnt = conf_matrix[lblid][lblid]
        lbl_acc = float(true_cnt)/float(overl_cnt) if overl_cnt > 0 else 1
        lbl_name = classes_dict[lblid] if lblid in classes_dict else "None"
        print "%s (%s) accuracy = %s"%(lbl_name.ljust(10), lblid, lbl_acc)

print_acc_from_conf_matrix(conf_matrix, classes_dict)
from sklearn.metrics import precision_recall_fscore_support

{1: 'O', 2: u'B-EVENT', 3: u'I-EVENT'}
None       (0) accuracy = 1.0
O          (1) accuracy = 0.5


In [31]:
import time as ti
from sklearn.metrics import precision_recall_fscore_support

# Initializing the variables
init = tf.initialize_all_variables()
sess = tf.InteractiveSession()

sess.run(init, feed_dict = None)



def prepare_batch_data(data, pad_value=0):
    batch_data_seqlens = [len(a.x) for a in data]
    max_len = max(batch_data_seqlens)

    batch_data_padded_x = [pad(a.x.tolist(), pad_value, max_len) for a in data]
    batch_data_padded_y = [pad(a.y.tolist(), pad_value, max_len) for a in data]
    # batch_data_padded_x_embedd = [[pad(a.x.tolist(), pad_value, max_len)] for a in batch_data]
    # batch_data_padded_y_mask = [[1 if item>0 else 0 for item in pad(a.y.tolist(), pad_value, max_len)] for a in batch_data]

    return batch_data_padded_x, batch_data_padded_y, batch_data_seqlens

def train_step(x_batch, y_batch, x_batch_seq_len):

    feed_dict = {
        embeddings_placeholder : embeddings_random,
        input_x : x_batch, # batch_data_padded_x,
        input_y : y_batch, # batch_data_padded_y,
        input_seq_len: x_batch_seq_len # batch_data_seqlens
    }

    #_, \
    _,\
    res_cost, \
    res_acc, \
    res_output_y,\
    res_mean_loss_by_example, \
    res_logits_flat,\
    res_losses, \
    res_probs_flat, \
    res_input_seq_len_float, \
    res_input_y_flat, res_bi_output_concat_flat, \
    res_output_fw, res_output_bw_reversed, res_embedded_chars, \
    res_weights_out, res_biases_out, \
    res_capped_gvs, \
    res_gvs \
    = sess.run([
                apply_grads_op,
                mean_loss, 
                accuracy, 
                preds_y, 
                mean_loss_by_example, 
                logits_flat,
                losses, 
                probs_flat,
                input_seq_len_float,
                input_y_flat, bi_output_concat_flat,
                output_fw, output_bw_reversed, embedded_chars,
                weights["out"], biases["out"],
                capped_gvs,
                gvs], 
               feed_dict=feed_dict)

    check_for_nans = True

    
    non_zero_input = [oy for oy in y_batch if 2 in oy]
    # print "Non_zero_input:%s" % len(non_zero_input)
    non_zero_preds = [oy for oy in res_output_y if 2 in oy]
    # print "Non-zero preds:%s" % len(non_zero_preds)
    
    # print non_zero_preds[:3]
    if check_for_nans:
        # print "res_input_seq_len_float:%s" % res_input_seq_len_float
        has_nans = False
        # res_output_concat =  sess.run(output_concat, feed_dict=feed_dict)
        # print res_output_concat.shape
        if np.isnan(np.sum(res_embedded_chars)):
            has_nans = True
            print "[res_embedded_chars] has nans!"

        if np.isnan(np.sum(res_output_fw)):
            has_nans = True
            print "[res_output_fw] has nans!"

        if np.isnan(np.sum(res_output_bw_reversed)):
            has_nans = True
            print "[res_output_bw_reversed] has nans!"

        if np.isnan(np.sum(res_bi_output_concat_flat)):
            has_nans = True
            print "[res_bi_output_concat_flat] has nans!"

        if np.isnan(np.sum(res_weights_out)):
            has_nans = True
            print "[res_weights_out] has nans!"

        if np.isnan(np.sum(res_biases_out)):
            has_nans = True
            print "[res_biases_out] has nans!"            

        if np.isnan(np.sum(res_logits_flat)):
            has_nans = True
            print "[res_logits_flat] has nans!"

        if np.isnan(np.sum(res_probs_flat)):
            has_nans = True
            print "[res_probs_flat] has nans!"

        if np.isnan(np.sum(res_losses)):
            has_nans = True
            print "[res_losses] has nans!"

        if np.isnan(np.sum(res_mean_loss_by_example)):
            has_nans = True
            print "[res_mean_loss_by_example] has nans!"

        if np.isnan(res_cost):
            has_nans = True
            print "[res_cost] has nans!"

#         if np.isnan(res_gvs):
#             has_nans = True
#             print "[res_gvs] has nans!"

#         if np.isnan(res_capped_gvs):
#             has_nans = True
#             print "[res_capped_gvs] has nans!"

        if has_nans:
            print "res_weights_out:%s" % res_weights_out[:5]
            print "res_biases_out:%s" % res_biases_out
            print "batch_data_padded_x:%s" % batch_data_padded_x[0]
            print "res_embedded_chars:%s" % len(res_embedded_chars), len(res_embedded_chars[0])
            print "res_output_fw:%s" % res_output_fw[0]
            print "res_output_bw_reversed:%s" % res_output_bw_reversed[0]
            # print "res_bi_output_concat_flat:%s" % res_bi_output_concat_flat
            print "res_input_y_flat:%s" % res_input_y_flat
            print "res_logits_flat:%s" % res_logits_flat
            print "res_res_probs_flat:%s" % res_probs_flat
            print "res_mean_loss_by_example:%s" % res_mean_loss_by_example
            print "res_losses:%s" % res_losses
            print "res_capped_gvs:%s" % res_capped_gvs
            print "res_gvs:%s" % res_gvs

            # print losses by example
            res_losses_reshaped = res_losses.reshape([50, res_losses.shape[0]/50])
            for i in range(len(res_losses_reshaped)):
                if np.isnan(np.sum(res_losses_reshaped[i])):
                    print res_losses_reshaped[i]
            raise Exception("Fucking NANS!")

    return res_cost, res_acc
        
def dev_step(x_batch, y_batch, x_batch_seq_len):
    
    feed_dict = {
        embeddings_placeholder : embeddings_random,
        input_x : x_batch, # batch_data_padded_x,
        input_y : y_batch, # batch_data_padded_y,
        input_seq_len: x_batch_seq_len # batch_data_seqlens
    }

    # _ ,\
    res_cost, \
    res_acc, \
    res_output_y,\
    res_mean_loss_by_example, \
    res_logits_flat,\
    res_losses, \
    res_probs_flat, \
    res_input_seq_len_float, \
    res_input_y_flat, res_bi_output_concat_flat, \
    res_output_fw, res_output_bw_reversed, res_embedded_chars, \
    res_weights_out, res_biases_out, \
    res_capped_gvs, \
    res_gvs \
    = sess.run([
                # apply_grads_op, - commented so does not apply gradients
                mean_loss, 
                accuracy, 
                preds_y,
                mean_loss_by_example, 
                logits_flat,
                losses, 
                probs_flat,
                input_seq_len_float,
                input_y_flat, bi_output_concat_flat,
                output_fw, output_bw_reversed, embedded_chars,
                weights["out"], biases["out"],
                capped_gvs,
                gvs
                ], 
               feed_dict=feed_dict)

    # print " Dev cost %2.2f | Dev batch acc %2.2f %% in %s\n" % (res_cost, res_acc, ti.time()-start),

    return res_output_y, res_cost, res_acc

pad_value = 0
train_batches_cnt = len(train_seq)/batch_size
dev_batches_cnt = len(dev_seq)/batch_size

print "Batches:%s" % train_batches_cnt
#batches_cnt = min(batches_cnt, 1)
epochs_cnt = 10
#train with batches
max_len = 0
print "Start training in %s epochs" % epochs_cnt
for epoch in range(0, epochs_cnt):
    print "Epoch %d:" % (epoch+1),
    start_epoch = ti.time()
    
    for i in range(0, train_batches_cnt):
        # print"Batch %s =================" % (i+1)
        
        #Get the batch
        batch_data = train_seq[i*batch_size:i*batch_size+batch_size]
        batch_data_padded_x, batch_data_padded_y, batch_data_seqlens = prepare_batch_data(data=batch_data)

        #Do the train step
        start = ti.time()
        cost, acc = train_step(x_batch = batch_data_padded_x, y_batch = batch_data_padded_y, x_batch_seq_len = batch_data_seqlens)
        # print " Train cost %2.2f | Train batch acc %2.2f %% in %s\n" % (cost, acc, ti.time()-start)
        
    print " train epoch time %s " % (ti.time()-start_epoch)
    #Dev eval - once per epoch
    input_y_all = []
    pred_y_all = []
    
    
    for i in range(0, dev_batches_cnt):
        batch_data = dev_seq[i*batch_size:i*batch_size+batch_size]
        batch_data_padded_x, batch_data_padded_y, batch_data_seqlens = prepare_batch_data(data=batch_data)
    
        res_pred_y, cost, acc = dev_step(x_batch = batch_data_padded_x, y_batch = batch_data_padded_y, x_batch_seq_len = batch_data_seqlens)
        
#         print batch_data_padded_y[10]
#         print res_pred_y[10]
        
        for j in range(0, batch_size):
            input_y_all.extend(batch_data_padded_y[j][:batch_data_seqlens[j]])
            pred_y_all.extend(res_pred_y[j][:batch_data_seqlens[j]])
            
            
    # eval
    print "Confusion matrix:"
    conf_matrix = confusion_matrix(input_y_all, pred_y_all)
    print conf_matrix
    print "Accuracy by class:"
    print_acc_from_conf_matrix(conf_matrix, classes_dict)
    
#     print "Class  : P, R, F-Score:" 
#     print "B-Event:"
#     print precision_recall_fscore_support(input_y_all, pred_y_all, average=None, pos_label=2)
#     print "I-Event:"
#     print precision_recall_fscore_support(input_y_all, pred_y_all, average=None, pos_label=3)
#     
    print " Dev cost %2.2f | Dev acc %2.2f %% in %s\n" % (cost, acc, ti.time()-start)
    

    

Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7fd14bf514d0>> ignored


Batches:251
Start training in 10 epochs
Epoch 1:  train epoch time 315.011768103 
Confusion matrix:
[[     0      0      0      0]
 [    42 164509    992      0]
 [     3   4267   2019      0]
 [     0    313     33      0]]
Accuracy by class:
None       (0) accuracy = 1
O          (1) accuracy = 0.993753888718
B-EVENT    (2) accuracy = 0.3210367308
I-EVENT    (3) accuracy = 0.0
 Dev cost 0.08 | Dev acc 0.98 % in 205.470056057

Epoch 2:  train epoch time 423.340708971 
Confusion matrix:
[[     0      0      0      0]
 [     4 164005   1534      0]
 [     2   2752   3535      0]
 [     0    271     75      0]]
Accuracy by class:
None       (0) accuracy = 1
O          (1) accuracy = 0.990709362522
B-EVENT    (2) accuracy = 0.562092542535
I-EVENT    (3) accuracy = 0.0
 Dev cost 0.08 | Dev acc 0.98 % in 203.339894056

Epoch 3:  train epoch time 315.096184015 
Confusion matrix:
[[     0      0      0      0]
 [     9 164487   1047      0]
 [     6   3067   3216      0]
 [     0    280     6

KeyboardInterrupt: 

In [32]:
# import time as ti
# pad_value = 0
# batches_cnt = len(train_seq)/batch_size
# print "Batches:%s" % batches_cnt
# #batches_cnt = min(batches_cnt, 1)

# # Initializing the variables
# init = tf.initialize_all_variables()
# sess = tf.InteractiveSession()
# sess.run(init, feed_dict = {embeddings_placeholder : embeddings_random})


# epochs_cnt = 10
# #train with batches
# print "Start training in %s epochs" % epochs_cnt
# for epoch in range(0, epochs_cnt):
#     print "Epoch %d:" % (epoch+1),
#     start = ti.time()
#     for i in range(0, batches_cnt):
#         print"batch %s =================" %(i+1)
#         #print i
#         batch_data = train_seq[i*batch_size:i*batch_size+batch_size]

#         batch_data_seqlens = [len(a.x) for a in batch_data]
#         #print data_lens
#         max_len = max(batch_data_seqlens)
#         #print max_len
#         batch_data_padded_x = [pad(a.x.tolist(), pad_value, max_len) for a in batch_data]
#         batch_data_padded_x_embedd = [[pad(a.x.tolist(), pad_value, max_len)] for a in batch_data]
#         batch_data_padded_y = [pad(a.y.tolist(), pad_value, max_len) for a in batch_data]
#         batch_data_padded_y_mask = [[1 if item>0 else 0 for item in pad(a.y.tolist(), pad_value, max_len)] for a in batch_data]

#         feed_dict = {
#             embeddings_placeholder : embeddings_random,
#             input_x : batch_data_padded_x,
#             input_y : batch_data_padded_y,
#             input_y_mask : batch_data_padded_y_mask,
#             input_seq_len: batch_data_seqlens
#         }

#         _, res_cost, res_acc, res_mean_loss_by_example, \
#                 res_losses, res_input_y_flat, res_bi_output_concat_flat,\
#             res_output_fw, res_output_bw_reversed, res_embedded_chars = \
#                  sess.run([optimizer, mean_loss, accuracy, mean_loss_by_example, 
#                            losses, input_y_flat, bi_output_concat_flat,
#                           output_fw, output_bw_reversed, embedded_chars], 
#                  feed_dict=feed_dict)
#         print "batch %s cost=%s, acc=%s:" %(i+1, res_cost, res_acc)
#         # res_output_concat =  sess.run(output_concat, feed_dict=feed_dict)
#         # print res_output_concat.shape
#         print "batch_data_padded_x:%s" % batch_data_padded_x[0]
#         has_nans =  np.isnan(np.sum(res_embedded_chars))
#         print "res_embedded_chars:%s" % len(res_embedded_chars), len(res_embedded_chars[0])
#         print "res_output_fw:%s" % res_output_fw[0]
#         print "res_output_bw_reversed:%s" % res_output_bw_reversed[0]
#         print "res_bi_output_concat_flat:%s" % res_bi_output_concat_flat
#         print "res_input_y_flat:%s" % res_input_y_flat
#         print "res_mean_loss_by_example:%s" % res_mean_loss_by_example
#         print "res_losses:%s" % res_losses
#         if has_nans:
#             raise Exception("Fucking NANS!")
    
#     print " Train cost %2.2f Train Acc %2.2f %% in %s\n" % (res_cost, res_acc, ti.time()-start),
#     #print batch_data_padded_x
#     #print batch_data_padded_y
    